# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8081
  connection-timeout: 5000ms
  servlet:
    context-path: /demo
    session:
      timeout: 86400 #60*60*24
      cookie:
        max-age: 86400 #60*60*24

spring:
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
  # 环境 dev|test|prod
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB #最大文件大小
      max-request-size: 100MB #最大数据请求
      enabled: true
  redis:
    open: false  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: localhost
    port: 6379
    password:    # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  mvc:
    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false
  activiti:
    database-schema-update: true #数据库执行的策略
    check-process-definitions: false #检查流程定义
    history-level: full #历史记录级别

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.cn.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ASSIGN_ID:"全局唯一ID (数字类型唯一ID)", ASSIGN_UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
      select-strategy: NOT_NULL
      #驼峰下划线转换
      table-underline: true
      #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: true
  #原生配置
  configuration:
    #驼峰转下划线
    map-underscore-to-camel-case: true
    #开启缓存
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

#配置日志
logging: 
  level: 
    #不同目录下的日志可配置不同级别
    org.springfromework.web: INFO
    org.hibernate: ERROR
  #采用相对路径方式将日志文件输出到【log/demo.log】
  file: log/demo.log
  pattern:
  #配置控制台日志显示格式
    console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n'
    #配置文件中日志显示格式
    file:  '%d{yyyy/MM/dd-HH:mm:ss}  [%thread] %-5level %logger- %msg%n'





